package enums;

public enum TipoGrupoMuscular {
    TORSO_INFERIOR_CUADRICEPS,
    TORSO_INFERIOR_ISQUIOTIBIALES,
    TORSO_INFERIOR_GLUTEOS,
    TORSO_INFERIOR_ADUCTORES,
    TORSO_INFERIOR_GEMELOS,
    TORSO_SUPERIOR_PECHO,
    TORSO_SUPERIOR_ESPALDA,
    TORSO_SUPERIOR_HOMBROS,
    TORSO_SUPERIOR_BICEPS,
    TORSO_SUPERIOR_TRICEPS,
    TORSO_MEDIO_ABDOMINALES,
    MULTIMUSCULAR
}
